clean: SCHUCK WELSCH DAVE_PLASMA
	pushd SCHUCK; \rm -f *.tex *.png *.eps *.fts *.txt; popd
	pushd WELSCH; \rm -f *.tex *.png *.eps *.fts *.txt; popd
	pushd DAVE_PLASMA; \rm -f *.tex *.png *.eps *.fts *.txt; popd




	
 